    version: '3.3'
    services:

      transaction-service:
        container_name: transaction-service
        build:
          context: .
          dockerfile: Dockerfile
        ports:
          - "2024:8085"
